### PR TITLE
Update nzbget.conf

### PR DESCRIPTION
**Pull request by LuisFlores3**

### CODE REVIEW

**Comment by hugbug** [comment]
Thank you for contribution.

I'm sure there is many more texts to fix or rewrite. How about that?

**Comment by LuisFlores3** [comment]
I will fix things as i stumble upon them. thanks for all you do. :0)

**Comment by hugbug** [comment]
Great, I'll wait then. Tell me when you have it finished.
And I'd rather prefer to put all changes into one commit instead of doing one commit per word :wink:

**Comment by war59312** [comment]
Few more:

https://github.com/war59312/nzbget/pull/1

**Comment by LuisFlores3** [comment]
Okay, so here is a first pass, mainly just spelling, and hyphens and such. Two notes:  
- Line 499, i think you wanted 'omitted', not 'limited'. (I changed)
- Lines 1070-1105, I am not sure if 'outputmode' is an internal referance (good as is) or if it is supposed to be 'output mode' (conversational), same with 'frontend' (vs. 'front end') (I left as-is)

**Comment by hugbug** [comment]
Great!
Should I merge or better wait for more corrections?

**Comment by LuisFlores3** [comment]
I'm not sure when i will have more time to take a better look at grammar and the like. It's a bigger thing. so it might be a couple of weeks... up to you really.

**Comment by hugbug** [comment]
OK, I'll merge it then (tomorrow).

**Pull request merged**
