### PR TITLE
#736: cast time_t to int for printf

### LINKED ISSUE #736: Segmentation fault on /jsonrpc
Potentially related to #621, except with `/jsonrpc/history?=false`, `/jsonrpc/listgroups`, and `/jsonrpc`. There is no output, unless the build is configured with `--enable-debug`.

When debug is enabled, here are the relevant lines in the log leading up to the crashes:

    Sun Feb 21 05:30:02 2021        254     3061509484      DEBUG   Final URL=/jsonrpc/history?=false (WebServer.cpp:240:ParseUrl)                                                                            
    Sun Feb 21 05:30:02 2021        254     3061509484      DEBUG   request received from 172.20.0.1 (WebServer.cpp:123:Execute)
    Sun Feb 21 05:30:02 2021        254     3061509484      DEBUG   MethodName=history (XmlRpc.cpp:418:Dispatch)          
    Sun Feb 21 05:30:02 2021        254     3061509484      ERROR   Segmentation fault

and:

    Sun Feb 21 05:30:22 2021        283     3062213996      DEBUG   [/jsonrpc/listgroups] [...] HTTP/1.1 304 Not Modified [...] (WebServer.cpp:545:SendBodyResponse)
    Sun Feb 21 05:30:22 2021        283     3062213996      DEBUG   Sending data (Connection.cpp:366:Send)
    Sun Feb 21 05:30:22 2021        283     3061849452      ERROR   Segmentation fault

and:

    Sun Feb 21 05:39:25 2021        299     3062607212      DEBUG   Final URL=/jsonrpc (WebServer.cpp:240:ParseUrl)
    Sun Feb 21 05:39:25 2021        299     3062607212      DEBUG   Request=[...] (WebServer.cpp:120:Execute)
    Sun Feb 21 05:39:25 2021        299     3062607212      DEBUG   request received from 172.20.0.3 (WebServer.cpp:123:Execute)
    Sun Feb 21 05:39:25 2021        299     3062607212      DEBUG   MethodName=history (XmlRpc.cpp:418:Dispatch)
    Sun Feb 21 05:39:25 2021        299     3062607212      ERROR   Segmentation fault

The [...] are my edits.

This is in a Docker container on Alpine 3.13, which appears to use musl 1.2.2, on a Raspberry Pi 4. I tested with 21.0, 21.1-r2311, and the tip of the dev branch. It worked fine on Alpine 3.12.

### PR DESCRIPTION
**Pull request by capntrips**
fixes #736

### CODE REVIEW

**Review by hugbug — CHANGES_REQUESTED** [review]
Thank you.

I would prefer if the fix would not touch format strings. The nzbget RPC-API is defined and should not be changed by the fix.

In order to merge the PR the following changes should be made:
- restore all format specifiers back to `%i`
- change all occurrences of `intmax_t` to `int`.

Please let me know if you prefer me to do the changes. In that case however I have to commit them directly and cannot merge the PR unfortunately (and you will not be indicated as the author of the commit).

**Comment by capntrips** [comment]
I'm happy to make the changes, but I'm away until early next week. I don't need any attribution, so if you feel compelled to make the fixes in the interim, feel free. Thanks.

**Comment by hugbug** [comment]
I prefer to preserve info about authors of contributions whenever possible.
I can wait, no problem.
Thank you.

**Comment by hugbug** [comment]
Thank you.

**Pull request merged**
