### PR TITLE
Fix for Issue #276

### PR DESCRIPTION
**Pull request by guaguasi**
Simple css tweak for #276

### CODE REVIEW

**Comment by hugbug** [comment]
At least on my monitor #FFFFF5 is hard to differentiate from white especially if only one row is selected. The following values work fine for me:

> tr.checked:nth-child(odd) .progress {
>   background-color: **#FFFFE8**;
>   }
> 
> .table-striped tbody tr.checked:nth-child(odd) td,
> .checked .progress {
>       background-color: **#FFFFD8**;

If you agree please update the PR and I'll merge it. Thank you.

**Comment by guaguasi** [comment]
Looks good to me, except I also darkened the hover color slightly:

`.table tbody tr.checked:hover,
.table tbody tr.checked:hover td {
        background-color: #FFFFC0;
}`

Thoughts?

**Comment by hugbug** [comment]
Looks good.

**Comment by hugbug** [comment]
Will you make a commit with the changes?

**Comment by guaguasi** [comment]
Had a busy weekend. We're good now.

**Pull request merged**
