### PR TITLE
Updated scripts to accept special characters in password

### PR DESCRIPTION
**Pull request by BernCarney**
Fix for #453

### CODE REVIEW

**Comment by hugbug** [comment]
Great. Thank you!

Can you please change it to quote the string when building rpcurl, not when assigning to variable `password` as that would be more logical. Also `username`must be quoted as well.

**Comment by BernCarney** [comment]
Will do.

**Review by BernCarney — COMMENTED** [review]
Updated PR

**Comment by hugbug** [comment]
Thanks for your contribution!

This dictionary feels like overkill 😄  Why not just use `quote`when building rpcUrl?
```python
rpcUrl = 'http://%s:%s@%s:%s/xmlrpc' % (quote(username), quote(password), host, port);
```

**Comment by BernCarney** [comment]
No problem!

Sometimes the simple solution is the last one you think of :P

**Comment by hugbug** [comment]
Would you like to commit a change for that or should I do it myself?

**Comment by BernCarney** [comment]
@hugbug all set

**Comment by hugbug** [comment]
Thank you!
Merged.

**Pull request merged**
