### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these LGTM [code quality badges](https://lgtm.com/projects/g/nzbget/nzbget/ci/#badges) to your project. They indicate how you care about code quality and encourage your future contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/nzbget/nzbget).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by hugbug** [comment]
Thank you.

I'm trying to configure LGTM integration to exclude third-party files from analysis. I need to exclude directories `lib` and `webui/lib` but no matter what I  do the checks for my PR #605 say "No alert changes". Many alerts should have gone away after ignoring library files but that doesn't happen.

Can it be that the new file `.lgtm.yml` which was added to the project as part of the PR doesn't have effect until merged into **develop** branch? However the [log](https://lgtm.com/projects/g/nzbget/nzbget/logs/rev/pr-84cd61c62ff9c5584545f5d1d72e608ca41c7f8d/lang:cpp/stage:Build%20merge%20(8dd9f40)) (tab "Extraction") for PR analysis **does** contain my changes to config file:

```
[2019-01-17 22:02:03] [build] Configuration file:
[2019-01-17 22:02:03] [build] path_classifiers:
[2019-01-17 22:02:03] [build]   library:
[2019-01-17 22:02:03] [build]     - "**/lib/"
[2019-01-17 22:02:03] [build]     - /lib
[2019-01-17 22:02:03] [build]     - /lib/
[2019-01-17 22:02:03] [build]     - "**/lib/*"
[2019-01-17 22:02:03] [build]     - "/lib/*"
[2019-01-17 22:02:03] [build]     - "lib/*"
[2019-01-17 22:02:03] [build]     - /webui/lib/
[2019-01-17 22:02:03] [build]     - /webui/lib
[2019-01-17 22:02:03] [build]     - webui/lib
[2019-01-17 22:02:03] [build]     - webui/lib/
[2019-01-17 22:02:03] [build]     - "/webui/lib/*"
[2019-01-17 22:02:03] [build]     - "webui/lib/*"
```

Yet no luck seeing changes to alerts number.

I hesitate to merge into **develop** until I know my config works.

**Comment by xcorail** [comment]
Hello @hugbug 

I am sorry for the confusion :(

Your PR is correct. But you won't see alerts go away *directly in this PR*. When there is such a change of the files exclusion / inclusion within the PR, we still report problems in the excluded code for this PR, to handle the case of a malicious contribution with a security vulnerability introduced at the same time as a an exclusion. We still want to warn the project reviewers in this case. 
But if you merge your PR, the exclusions will be taken into account just after. You will see `lib` and `webui\lib` as excluded files, and the next analysis won't display errors there.

BTW, you don't need the 3 last lines in your file.

Cheers, tell me how it goes

**Comment by hugbug** [comment]
Thank you very much for the very quick response!

I was trying different syntaxes, that's why there are many (unnecessary) entries.

In my very first attempt I was using only one entry:
```yml
path_classifiers:
  library:
    - "**/lib/"
```

Should this work?

Or maybe it's better to use explicit names without wildcards instead?:
```yml
path_classifiers:
  library:
    - lib
    - webui/lib
```

**Comment by xcorail** [comment]
> Thank you very much for the very quick response!

You're welcome! (Also don't hesitate to ask for support at https://discuss.lgtm.com/ in case I am busy and cannot answer you quickly)

Both your suggestions will work, but I would go for the explicit one, in case a contributor adds a new `lib` subdirectory in the future within actual production code. In this case it won't be analyzed, and this will be unnoticed by you.

Cheers

**Comment by xcorail** [comment]
BTW @hugbug the same logic stands for the alerts suppressions: if some contributor adds this code

`some_malicious_security_backdoor(); // LGTM`

Then LGTM will still report a security alert during the PR analysis, despite the suppression comment `//LGTM`.

**Comment by hugbug** [comment]
@xcorail thank you for the explanation. This all makes sense.

I wish there were a way to check custom branches, ideally every commit in every branch like Travis CI does.

When I develop a new feature or even a bugfix I do that in a separate branch, usually local branch. Then I push it to GitHub and wait for Travis CI to do the checks. My project contains a number of tests which are all run on Travis CI (and several compiler versions). Sometimes compilation fails on an older GCC version (I have an extra config on Travis CI to compile with GCC 4.8) or tests fail (if I forget to run them locally before committing). Travis CI catches that and I know about problems before merging into develop branch. When I know that compilation and tests on all Travis CI configs succeeded I can merge the branch into develop.

It would be very useful if LGTM would support the same workflow. Large teams may use pull requests for internal merging; especially if another developer can do review. Most small teams (or individual developers) don't create pull requests for themselves. Even If I would create PR for myself the PR is created when the feature is completed and that may take a long time. With checks for every commit I would be informed about issues much sooner, during development of the feature.

Thanks again for your support and for taking time to import NZBGet into LGTM and posting the pull request. I'm merging the PR.

**Pull request merged**
