### PR TITLE
NServ: opton -b to define address to listen to

### PR DESCRIPTION
**Pull request by sanderjo**
For example:

`-b ::` to listen to IPv6 and IPv4
`-b 127.0.0.1`  to listen to IPv4 localhost only   

Default is still 0.0.0.0

### CODE REVIEW

**Comment by hugbug** [comment]
Something is wrong with this PR as it contains a commit already merged with another PR.

**Comment by sanderjo** [comment]
I can send a new PR with only the new commit. Is that OK?

**Comment by hugbug** [comment]
Either that or somehow rebase/reset/whatever this PR. Thanks.

**Comment by hugbug** [comment]
Merged in another PR.

**Pull request closed without merging**
