### PR TITLE
Fix for Issue #29

### PR DESCRIPTION
**Pull request by guaguasi**
Took a little longer than I planned. Refactored twice. Hopefully worth it lol.

Adds more robust pause control as requested in issue #29

### CODE REVIEW

**Comment by hugbug** [comment]
Great job you did!

I have one suggestion - the table with examples is useful but scares a bit (too much info). I would prefer a one sentence help (something like `For example "30m", "2h" or "=18:00"`) and button "Quick help" which shows the full help screen in a separate dialog, like in the "Add files dialog".

**Comment by guaguasi** [comment]
The examples are really the only formats accepted. I'll do as you say and add the table in a "Quick help" style section and that sentence where the table is currently.

I'll get to it when I have some time, most likely this weekend. If I can manage, I'll do it tonight or tomorrow night.

**Comment by hugbug** [comment]
A small thing: when the preview text appears or hides the dialog height changes. It'd be better to keep the height constant. May be some explanaition text in the preview box or just keep it empty but still visible to prevent height changes.

I've also noticed that opening the dialog for second time shows a preview text from previous usage.

**Comment by guaguasi** [comment]
Ended up just doing it. Let me know if there are anything else.

**Pull request merged**
